---
Name: solrcloud
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Marcz\Solr\SolrAdminExtension

Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Solr\Extensions\Exporter

Marcz\Search\Config:
  clients:
    - name: 'Solr'
      write: true
      delete: true
      export: 'json'
      class: 'Marcz\Solr\SolrClient'
Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Solr\Extensions\Exporter
